repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

      - id: mixed-line-ending
        args: [--fix=lf]

  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black

  # Disabled as there are currently type checking errors
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.720
  #   hooks:
  #   - id: mypy
  #     args: [--ignore-missing-imports, --strict-equality, --warn-unreachable]
