language: python

python:
  - "3.6"

cache:
  pip: true
  directories:
    - "$HOME/.cache/pypoetry"
    - "$HOME/.cache/pre-commit"

install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source "$HOME/.poetry/env"
  - poetry install -v
  - pip3 install black pre-commit

script:
  # Run Black manually first to get a diff in the CI output in case of failure
  - black *.py --diff
  - pre-commit run --all-files
